#!/bin/bash
DIST_HOME="$(dirname $(readlink $0 || echo $0))/.."
TEST_JAR=$DIST_HOME/@DIST_NAME@-@VERSION@-test.jar
java -server -classpath @TEST_CLASSPATH@:$TEST_JAR com.twitter.libkestrel.load.QTest "$@"

